name: hepa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ">=3.3.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adaptive_theme: ^3.6.0
  chat_bubbles: ^1.6.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_riverpod: ^2.5.1
  flutter_widget_from_html: ^0.15.0
  freezed_annotation: ^2.4.1
  go_router: ^14.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path: ^1.9.0
  permission_handler: ^11.3.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  pusher_channels_flutter: ^2.2.1
  radio_group_v2: ^3.1.0
  riverpod_annotation: ^2.3.5
  searchable_listview: ^2.11.2
  sentry: ^8.1.0
  sentry_flutter: ^8.1.0
  sentry_logging: ^8.1.0
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.2+1
  tab_container: ^3.5.3
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - shorebird.yaml
