name: hepa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_local_notifications: ^17.0.0
  flutter_widget_from_html: ^0.14.11
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path: ^1.9.0
  permission_handler: ^11.3.0
  pretty_dio_logger: ^1.3.1
  radio_group_v2: ^3.1.0
  refreshed: ^2.5.8
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.0
  webviewtube: ^2.0.0
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/
  uses-material-design: true
