// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjX2a_mef1hHA9bdthxuwDvwLyn9wrPKU',
    appId: '1:538614402782:android:182a37b1159381d6f63c4f',
    messagingSenderId: '538614402782',
    projectId: 'healthplanner-50981',
    storageBucket: 'healthplanner-50981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLryUjzW0mHHmr4r1iQgdOsYtSwyG44aM',
    appId: '1:538614402782:ios:fbc10f2ab04e95d3f63c4f',
    messagingSenderId: '538614402782',
    projectId: 'healthplanner-50981',
    storageBucket: 'healthplanner-50981.appspot.com',
    iosBundleId: 'com.example.hepa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkaFqhp-7Ch8hsTkDWdqDPfiBxwByRBQs',
    appId: '1:538614402782:web:caf11e83df149e24f63c4f',
    messagingSenderId: '538614402782',
    projectId: 'healthplanner-50981',
    authDomain: 'healthplanner-50981.firebaseapp.com',
    storageBucket: 'healthplanner-50981.appspot.com',
    measurementId: 'G-BKL2TNH2LR',
  );
}
